### ISSUE TITLE
extracting //kythe/cxx/... fails

### ISSUE THREAD

**Issue by salguarnieri** [kythe/kythe#4502]
In https://kythe.io/examples/#extracting-the-kythe-repository we tell people they can run `bazel build -k \
  --experimental_action_listener=@io_kythe//kythe/extractors:extract_kzip_java \
  --experimental_action_listener=@io_kythe//kythe/extractors:extract_kzip_cxx \
  --experimental_extra_action_top_level_only \
  //kythe/cxx/... //kythe/java/...` but this doesn't work any longer.

For example:

```
$ bazel build  --experimental_action_listener=@io_kythe//kythe/extractors:extract_kzip_cxx   --experimental_extra_action_top_level_only   //kythe/cxx/indexer/cxx/testdata/proto/...
INFO: Build option --experimental_action_listener has changed, discarding analysis cache.
INFO: Analyzed 24 targets (0 packages loaded, 13818 targets configured).
INFO: Found 24 targets...
ERROR: .../kythe/kythe/testdata/indexers/proto/BUILD:39:1: C++ compilation of rule '//kythe/testdata/indexers/proto:testdata4a_proto' failed (Exit 1) clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++17' -MD -MF ... (remaining 33 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from bazel-out/k8-fastbuild/bin/kythe/testdata/indexers/proto/testdata4a.pb.cc:4:
bazel-out/k8-fastbuild/bin/kythe/testdata/indexers/proto/testdata4a.pb.h:35:10: fatal error: 'kythe/testdata/indexers/proto/testdata4c.pb.h' file not found
#include "kythe/testdata/indexers/proto/testdata4c.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR: .../kythe/kythe/testdata/indexers/proto/BUILD:39:1 C++ compilation of rule '//kythe/testdata/indexers/proto:testdata4a_proto' failed (Exit 1) clang failed: error executing command /usr/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++17' -MD -MF ... (remaining 33 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 1.958s, Critical Path: 0.75s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by salguarnieri** [comment]
I think 90f7c4e0a696d91de8a00d2e33d85806a268996f is the first bad commit. @jaysachs

**Comment by jaysachs** [comment]
I'll try to find some time to debug this soon.

**Comment by salguarnieri** [comment]
For a workaround we could either change the documentation to be more precise in what we recommend to extract or we could mark those targets as manual like in https://github.com/salguarnieri/kythe/tree/no-glob-for-now.
